# docker-compose.yml
version: '3.8'

services:
  game-server:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./style.css:/usr/share/nginx/html/style.css
      - ./script.js:/usr/share/nginx/html/script.js
    container_name: autumn-escape-game
    